=== CodeFromAnywhere/actionschema-ref/public/flat-object-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "type": {
      "const": "object"
    },
    "properties": {
      "type": "object",
      "properties": {
        "$schema": {
          "type": "object",
          "properties": {
            "type": {
              "const": "string"
            },
            "format": {
              "const": "uri-reference"
            }
          },
          "required": ["type", "format"],
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "additionalProperties": {
      "type": "object",
      "properties": {
        "anyOf": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "type": {
                  "type": "array",
                  "items": {
                    "enum": ["boolean", "number", "null", "string"]
                  },
                  "minItems": 1,
                  "uniqueItems": true
                }
              },
              "required": ["type"],
              "additionalProperties": false
            },
            {
              "type": "object",
              "properties": {
                "type": {
                  "const": "array"
                },
                "minLength": {
                  "const": 1
                },
                "items": {
                  "type": "object",
                  "properties": {
                    "oneOf": {
                      "type": "array",
                      "items": [
                        {
                          "type": "object",
                          "properties": {
                            "type": {
                              "type": "array",
                              "items": {
                                "enum": ["boolean", "number", "null", "string"]
                              },
                              "minItems": 1,
                              "uniqueItems": true
                            }
                          },
                          "required": ["type"],
                          "additionalProperties": false
                        },
                        {
                          "type": "object",
                          "properties": {
                            "type": {
                              "const": "object"
                            },
                            "additionalProperties": {
                              "type": "object",
                              "properties": {
                                "type": {
                                  "type": "array",
                                  "items": {
                                    "enum": [
                                      "boolean",
                                      "number",
                                      "null",
                                      "string"
                                    ]
                                  },
                                  "minItems": 1,
                                  "uniqueItems": true
                                }
                              },
                              "required": ["type"],
                              "additionalProperties": false
                            }
                          },
                          "required": ["type", "additionalProperties"],
                          "additionalProperties": false
                        }
                      ],
                      "minItems": 2,
                      "maxItems": 2
                    }
                  },
                  "required": ["oneOf"],
                  "additionalProperties": false
                }
              },
              "required": ["type", "minLength", "items"],
              "additionalProperties": false
            }
          ],
          "minItems": 2,
          "maxItems": 2
        }
      },
      "required": ["anyOf"],
      "additionalProperties": false
    }
  },
  "required": [
    "$schema",
    "description",
    "type",
    "properties",
    "additionalProperties"
  ],
  "additionalProperties": false
}

=== CodeFromAnywhere/actionschema-ref/public/flat-object.json
{
  "$schema": "https://spec.actionschema.com/actionschema.json",
  "description": "This is at the core of the simplification. A flat object is a subset of JSON-Schema that doesn't allow for recursion in the JSON object, effectively allowing for easier manipulation of everything defined with these constraints. It can be used for validating data.",
  "type": "object",
  "properties": {
    "$schema": { "type": "string", "format": "uri-reference" }
  },
  "additionalProperties": {
    "anyOf": [
      {
        "type": ["boolean", "number", "null", "string"]
      },
      {
        "type": "array",
        "minLength": 1,
        "items": {
          "oneOf": [
            {
              "type": ["boolean", "number", "null", "string"]
            },
            {
              "type": "object",
              "additionalProperties": {
                "type": ["boolean", "number", "null", "string"]
              }
            }
          ]
        }
      }
    ]
  }
}
